Remove hwx.public.repo maven repo
The hwx.public.repo (nexus-private.hortonworks.com) contains jars that
conflict with impala.cdh.repo (GBN based s3 bucket). This means that
Impala can build and test with a mix of jars from both. The latest
symptom of this is frontend tests failing with messages like:
java.lang.NoClassDefFoundError: org/apache/hadoop/security/ssl/OpenSSLSocketFactory$SSLChannelMode
This happens because hadoop-aws is on a more recent version than
hadoop-common.

Since Impala builds without the hwx.public.repo, let's remove it.

Change-Id: I6f1cf7efcad522c2df228c8c2b8068bb3002e407
Reviewed-on: http://gerrit.cloudera.org:8080/13403
Reviewed-by: Fredy Wijaya <fwijaya@cloudera.com>
Tested-by: Joe McDonnell <joemcdonnell@cloudera.com>