Exclude kafka dependency from ranger-plugins-audit
This patch excludes kafka dependency from ranger-plugins-audit to avoid
jax-rs version conflict due to kafka transitively pulling pulling an
incompatible version of jax-rs dependency used in Impala. See
RANGER-2426.

I was able to find an issue by manually modifying the CLASSPATH to force
jax-rs 2.1 (from Kafka) to be loaded first and saw a
java.lang.NoClassDefFoundError: javax/ws/rs/core/Link$Builder.

Testing:
- After removing kafka dependency, I did not see any jersey-server 2.27
  in the CLASSPATH and was able to start Impala with Ranger without any
  error.

Change-Id: I4a01f34d078c50bc22fc67a67415a1e6e9c87151
Reviewed-on: http://gerrit.cloudera.org:8080/13322
Reviewed-by: Fredy Wijaya <fwijaya@cloudera.com>
Tested-by: Impala Public Jenkins <impala-public-jenkins@cloudera.com>